let products = [
    {
        name: 'Nintendo Game-boy',
        img: './assets/nintendo-game-boy.jpg',
        tag: 'nintendo-game-boy',
        title: '6 Title',
        available: 'Available',
        price: 200,
        inCart: 0,
        id: 0,
    },
    {
        name: 'Nintendo shoot',
        img: './assets/nintendo-shoot.jpg',
        tag: 'nintendo-shoot',
        title: '2 Title',
        available: 'Available',
        price: 180,
        inCart: 0,
        id: 1,
    },
    {
        name: 'Nintendo switch',
        img: './assets/nintendo-switch.jpg',
        tag: 'nintendo-switch',
        title: '3 Title',
        available: 'Available',
        price: 375,
        inCart: 0,
        id: 2,
    },
    {
        name: 'Playstation',
        img: './assets/playstation1.jpg',
        tag: 'playstation',
        title: '56 Title',
        available: 'Available',
        price: 200,
        inCart: 0,
        id: 3,
    },
    {
        name: 'Playstation2',
        img: './assets/playstation2.jpg',
        tag: 'playstation2',
        title: '5 Title',
        available: 'Available',
        price: 80,
        inCart: 0,
        id: 4,
    },
    {
        name: 'Playstation3',
        img: './assets/playstation3.jpg',
        tag: 'playstation3',
        title: '1 Title',
        available: 'Available',
        price: 175,
        inCart: 0,
        id: 5,
    },
    {
        name: 'Playstation4',
        img: './assets/playstation4.jpg',
        tag: 'playstation4',
        title: '7 Title',
        available: 'Available',
        price: 350,
        inCart: 0,
        id: 6,
    },
    {
        name: 'Playstation5',
        img: './assets/playstation5.jpg',
        tag: 'playstation5',
        title: '13 Title',
        available: 'Available',
        price: 500,
        inCart: 0,
        id: 7,
    },
    {
        name: 'PSP',
        img: './assets/psp.jpg',
        tag: 'psp',
        title: '9 Title',
        available: 'Available',
        price: 100,
        inCart: 0,
        id: 8,
    },
    {
        name: 'PS-Vita',
        img: './assets/psvita.jpg',
        tag: 'ps-vita',
        title: '10 Title',
        available: 'Not Available',
        price: 225,
        inCart: 0,
        id: 9,
    },
    {
        img: './assets/sega.jpg',
        name: 'Sega',
        tag: 'sega',
        title: '11 Title',
        available: 'Available',
        price: 115,
        inCart: 0,
        id: 10,
    },
    {
        img: './assets/super-nintendo.jpg',
        name: 'Super-nintendo',
        tag: 'super-nintendo',
        title: ' 12 Title',
        available: 'Available',
        price: 100,
        inCart: 0,
        id: 11,
    },
    {
        name: 'X-BOX',
        img: './assets/x-box1.jpg',
        tag: 'x-box',
        title: ' 8 Title',
        available: 'Available',
        price: 125,
        inCart: 0,
        id: 12,
    },
    {
        name: 'X-BOX 360',
        img: './assets/x-box360.jpg',
        tag: 'x-box-360',
        title: ' 286 Title',
        available: 'Available',
        price: 200,
        inCart: 0,
        id: 13,
    },
    {
        name: 'X-BOX One',
        img: './assets/x-boxOne.jpg',
        tag: 'x-box-one',
        title: ' 99 Title',
        available: 'Not Available',
        price: 325,
        inCart: 0,
        id: 14,
    },
    {
        name: 'X-BOX SeriesX',
        img: './assets/x-boxSeriesX.jpg',
        tag: 'x-box-series-x',
        title: '16 Title',
        available: 'Available',
        price: 400,
        inCart: 0,
        id: 15,
    },
];