let products = [
    {
        name: 'Playstation4',
        img: './assets/playstation4.jpg',
        tag: 'playstation4',
        title: 'Title: 4378',
        availableName: 'Available',
        available: true,
        brandOfProduct: 'Brand: Sony',
        productDescription: 'Standart console',
        price: 350,
        inCart: 0,
        id: 6,
    },
    {
        name: 'Nintendo shoot',
        img: './assets/nintendo-shoot.jpg',
        tag: 'nintendo-shoot',
        title: 'Title: 5433',
        availableName: 'Not Available',
        available: false,
        brandOfProduct: 'Brand: Nintendo',
        productDescription: 'Standart console',
        price: 180,
        inCart: 0,
        id: 1,
    },
    {
        name: 'Nintendo switch',
        img: './assets/nintendo-switch.jpg',
        tag: 'nintendo-switch',
        title: 'Title: 5434',
        availableName: 'Available',
        available: true,
        brandOfProduct: 'Brand: Nintendo',
        productDescription: 'Portable gaming console',
        price: 375,
        inCart: 0,
        id: 2,
    },
    {
        name: 'Playstation',
        img: './assets/playstation1.jpg',
        tag: 'playstation',
        title: 'Title: 5435',
        availableName: 'Available',
        available: true,
        brandOfProduct: 'Brand: Sony',
        productDescription: 'Standart console',
        price: 200,
        inCart: 0,
        id: 3,
    },
    {
        name: 'Playstation2',
        img: './assets/playstation2.jpg',
        tag: 'playstation2',
        title: 'Title: 5436',
        availableName: 'Available',
        available: true,
        brandOfProduct: 'Brand: Sony',
        productDescription: 'Standart console',
        price: 80,
        inCart: 0,
        id: 4,
    },
    {
        name: 'Playstation3',
        img: './assets/playstation3.jpg',
        tag: 'playstation3',
        title: 'Title: 5437',
        availableName: 'Available',
        available: true,
        brandOfProduct: 'Brand: Sony',
        productDescription: 'Standart console',
        price: 175,
        inCart: 0,
        id: 5,
    },
    {
        name: 'Nintendo Game-boy',
        img: './assets/nintendo-game-boy.jpg',
        tag: 'nintendo-game-boy',
        title: 'Title: 5432',
        availableName: 'Available',
        available: true,
        brandOfProduct: 'Brand: Nintendo',
        productDescription: 'Portable gaming console',
        price: 200,
        inCart: 0,
        id: 0,
    },
    {
        name: 'Playstation5',
        img: './assets/playstation5.jpg',
        tag: 'playstation5',
        title: 'Title: 5438',
        availableName: 'Available',
        available: true,
        brandOfProduct: 'Brand: Sony',
        productDescription: 'Standart console',
        price: 500,
        inCart: 0,
        id: 7,
    },
    {
        name: 'PSP',
        img: './assets/psp.jpg',
        tag: 'psp',
        title: 'Title: 5439',
        availableName: 'Available',
        available: true,
        brandOfProduct: 'Brand: Sony',
        productDescription: 'Portable gaming console',
        price: 100,
        inCart: 0,
        id: 8,
    },
    {
        name: 'PS-Vita',
        img: './assets/psvita.jpg',
        tag: 'ps-vita',
        title: 'Title: 5440',
        availableName: 'Not Available',
        available: false,
        brandOfProduct: 'Brand: Sony',
        productDescription: 'Portable gaming console',
        price: 225,
        inCart: 0,
        id: 9,
    },
    {
        name: 'Sega',
        img: './assets/sega.jpg',
        tag: 'sega',
        title: 'Title: 5441',
        availableName: 'Available',
        available: true,
        brandOfProduct: 'Brand: Sony',
        productDescription: 'Standart console',
        price: 115,
        inCart: 0,
        id: 10,
    },
    {
        name: 'Super-nintendo',
        img: './assets/super-nintendo.jpg',
        tag: 'super-nintendo',
        title: 'Title: 5442',
        availableName: 'Available',
        available: true,
        brandOfProduct: 'Brand: Nintendo',
        productDescription: 'Standart console',
        price: 100,
        inCart: 0,
        id: 11,
    },
    {
        name: 'X-BOX',
        img: './assets/x-box1.jpg',
        tag: 'x-box',
        title: 'Title: 5443',
        availableName: 'Available',
        available: true,
        brandOfProduct: 'Brand: Microsoft',
        productDescription: 'Standart console',
        price: 125,
        inCart: 0,
        id: 12,
    },
    {
        name: 'X-BOX 360',
        img: './assets/x-box360.jpg',
        tag: 'x-box-360',
        title: 'Title: 5444',
        availableName: 'Available',
        available: true,
        brandOfProduct: 'Brand: Microsoft',
        productDescription: 'Standart console',
        price: 200,
        inCart: 0,
        id: 13,
    },
    {
        name: 'X-BOX One',
        img: './assets/x-boxOne.jpg',
        tag: 'x-box-one',
        title: 'Title: 5445',
        availableName: 'Not Available',
        available: false,
        brandOfProduct: 'Brand: Microsoft',
        productDescription: 'Standart console',
        price: 325,
        inCart: 0,
        id: 14,
    },
    {
        name: 'X-BOX SeriesX',
        img: './assets/x-boxSeriesX.jpg',
        tag: 'x-box-series-x',
        title: 'Title: 5446',
        availableName: 'Available',
        available: true,
        brandOfProduct: 'Brand: Microsoft',
        productDescription: 'Standart console',
        price: 400,
        inCart: 0,
        id: 15,
    },
];